import {HowItWorks} from './HowItWorks';
import {LanguageShowcase} from './LanguageShowcase';
import {LandingFeatures} from './LandingFeatures';
import {BrandLogo} from './BrandLogo';
import {ArrowRight} from 'lucide-react';
import {type Language} from './courses';
import './landing.css';import './landing-hero.css';import './landing-ending.css';
type Props={language:Language;onLanguage:(language:Language)=>void;onStart:()=>void;signedIn:boolean;busy?:boolean};
export function Landing({language,onLanguage,onStart,busy=false}:Props){return <main className="landing"><section className="premium-hero companion-hero" aria-label="Learn Nigerian languages"><div className="hero-content"><span className="hero-kicker">LEARN • PRACTICE • CONNECT</span><h1>Learn the languages.<br/><span>Live the culture.</span></h1><p>Learn Yorùbá, Igbo and Hausa through practical lessons, real conversations and Nigerian cultural context.</p><div className="hero-ctas"><button className="hero-start" disabled={busy} onClick={onStart}>Start Learning Free <ArrowRight size={21} aria-hidden="true"/></button></div></div><div className="hero-companions" aria-label="Meet your language companions">{([{id:'ade',name:'Adé',language:'Yorùbá',alt:'Adé in a blue agbádá and patterned fìlà'},{id:'ada',name:'Ada',language:'Igbo',alt:'Ada in a patterned outfit and red headwrap with coral beads'},{id:'amina',name:'Amina',language:'Hausa',alt:'Amina in a green outfit and headscarf with gold embroidery'}]).map(companion=><figure className={`hero-companion hero-companion-${companion.id}`} key={companion.id}><img src={`/brand/${companion.id}.png`} alt={companion.alt} width="1254" height="1254" fetchPriority="high"/><figcaption><strong>{companion.name}</strong><span>{companion.language} companion</span></figcaption></figure>)}</div></section><LandingFeatures/>
<LanguageShowcase language={language} onLanguage={onLanguage} busy={busy}/>
<HowItWorks/>
<section className="landing-final" aria-labelledby="landing-final-title"><div className="landing-final-inner"><h2 id="landing-final-title">There’s a whole world in your next hello.</h2><p>Start learning Yorùbá, Igbo or Hausa today.</p><button disabled={busy} onClick={onStart}>Start Learning Free <ArrowRight size={21} aria-hidden="true"/></button></div></section><footer className="landing-footer"><BrandLogo/><p>© 2026 LingoNaija · Real conversations. Richer connections.</p></footer></main>}
